services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mydb:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - vipvol:/var/lib/postgresql/data

  end:
    image: lunch:v6
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=end.vcap.me
      - TITLE=END
      - COLOR=cyan
  dinner:
    image: lunch:v6
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=dinner.vcap.me
      - TITLE=Dinner
      - COLOR=yellow
  front:
    image: cmd.cat/bash/dig/curl/psql
    command: sleep 9999

volumes:
  vipvol: